package com.example.util

object AppLocalization {

    fun tr(key: String, language: String): String {
        val lang = language.lowercase()
        return when {
            lang.contains("telugu") || lang.contains("te") || lang.contains("తెలుగు") -> getTelugu(key)
            lang.contains("hindi") || lang.contains("hi") || lang.contains("हिंदी") -> getHindi(key)
            lang.contains("tamil") || lang.contains("ta") || lang.contains("தமிழ்") -> getTamil(key)
            lang.contains("kannada") || lang.contains("kn") || lang.contains("కన్నడ") || lang.contains("ಕನ್ನಡ") -> getKannada(key)
            lang.contains("malayalam") || lang.contains("ml") || lang.contains("മലയാളം") -> getMalayalam(key)
            else -> getEnglish(key)
        }
    }

    private fun getEnglish(key: String): String {
        return when (key) {
            "app_name" -> "CropCare AI"
            "nav_home" -> "Dashboard"
            "nav_irrigation" -> "Smart Irrigation"
            "nav_scan" -> "Crop Disease"
            "nav_yield" -> "Yield Prediction"
            "nav_weather" -> "Weather & Soil"
            "nav_chat" -> "AI Assistant"
            "nav_settings" -> "Settings"

            // Dashboard
            "greeting" -> "Namaste"
            "pro_farmer" -> "Pro Farmer"
            "health_score" -> "Health Score"
            "hero_title" -> "Smart AI Farm Grid"
            "hero_subtitle" -> "ESP32 Live IoT Sensors Active"
            "weather_widget_title" -> "Today's Weather"
            "live_sensors" -> "Live Sensors"
            "soil_moisture" -> "Soil Moisture"
            "water_tank" -> "Water Tank"
            "soil_temp" -> "Soil Temperature"
            "soil_ph" -> "Soil pH"
            "soil_npk" -> "Soil NPK Balance"
            "motor_status" -> "Motor Pump Status"
            "motor_on" -> "Motor ON"
            "motor_off" -> "Motor OFF"
            "quick_actions" -> "Quick Actions"
            "latest_scan" -> "Latest Crop Scan"
            "expected_yield" -> "Expected Yield"
            "notifications" -> "Farm Notifications"

            // Disease Scan
            "scan_title" -> "AI Crop Disease Detection"
            "upload_image" -> "Upload Plant Image"
            "take_photo" -> "Take Photo"
            "choose_gallery" -> "Choose from Gallery"
            "analyzing" -> "Analyzing image with Gemini AI..."
            "quality_error_title" -> "Image Quality Check Failed"
            "quality_error_msg" -> "Please upload a clear image of a single affected leaf or plant."
            "low_confidence_msg" -> "Unable to identify the disease accurately. Please upload a clearer image."
            "healthy_plant" -> "Healthy Plant"
            "no_disease" -> "No disease detected. Plant is in optimal health."
            "report_title" -> "AI Disease Analysis Report"
            "disease_name" -> "Disease Name"
            "confidence" -> "Confidence Score"
            "severity" -> "Severity Level"
            "affected_part" -> "Affected Plant Part"
            "symptoms" -> "Visible Symptoms"
            "causes" -> "Possible Causes"
            "treatment" -> "Recommended Treatment"
            "fungicide" -> "Recommended Fungicide / Pesticide"
            "organic" -> "Organic Solution"
            "prevention" -> "Preventive Measures"
            "recovery" -> "Expected Recovery Time"
            "farmer_advice" -> "Farmer Advice"
            "crop_rec" -> "Crop Identification"
            "growth_stage" -> "Growth Stage"
            "plant_age" -> "Plant Age"
            "listen_voice" -> "Listen in Selected Language"
            "stop_voice" -> "Stop Voice"

            // Smart Irrigation
            "irrigation_title" -> "Smart Automated Irrigation"
            "auto_mode" -> "Auto Threshold Mode"
            "manual_mode" -> "Manual Mode"
            "water_usage" -> "Water Usage"
            "last_irrigation" -> "Last Irrigation"
            "next_irrigation" -> "Next Recommended Irrigation"
            "liters" -> "Liters"

            // Yield Prediction
            "yield_title" -> "AI Crop Yield Prediction"
            "acres" -> "Farm Size (Acres)"
            "seed_variety" -> "Seed Variety"
            "expected_harvest" -> "Expected Harvest Date"
            "market_price" -> "Estimated Market Price"
            "est_income" -> "Estimated Gross Income"
            "est_expenses" -> "Estimated Expenses"
            "net_profit" -> "Estimated Net Profit"
            "risk_level" -> "Risk Level"
            "yield_suggestions" -> "Suggestions to Increase Yield"

            // Weather
            "weather_title" -> "Weather Forecast & Climate"
            "rain_prob" -> "Rain Probability"
            "wind_speed" -> "Wind Speed"
            "uv_index" -> "UV Index"
            "sunrise" -> "Sunrise"
            "sunset" -> "Sunset"
            "forecast_7day" -> "7-Day Weather Forecast"
            "weather_irrigation_advice" -> "Weather-based Irrigation Advice"

            // Settings
            "settings_title" -> "Settings & Preferences"
            "theme_mode" -> "App Theme"
            "light_theme" -> "Light Theme (White)"
            "dark_theme" -> "Dark Theme (Black)"
            "select_language" -> "Select Language"
            "farmer_profile" -> "Farmer Profile"
            "save_profile" -> "Save Profile"
            "logout" -> "Logout Account"

            else -> key
        }
    }

    private fun getTelugu(key: String): String {
        return when (key) {
            "app_name" -> "క్రాప్‌కేర్ AI"
            "nav_home" -> "హోమ్"
            "nav_irrigation" -> "స్మార్ట్ నీటిపారుదల"
            "nav_scan" -> "పంట వ్యాధులు"
            "nav_yield" -> "దిగుబడి అంచనా"
            "nav_weather" -> "వాతావరణం"
            "nav_chat" -> "AI సలహాదారు"
            "nav_settings" -> "సెట్టింగ్‌లు"

            "greeting" -> "నమస్తే"
            "pro_farmer" -> "ప్రో రైతు"
            "health_score" -> "ఆరోగ్య స్కోరు"
            "hero_title" -> "స్మార్ట్ ఫార్మ్ నెట్‌వర్క్"
            "hero_subtitle" -> "ESP32 ప్రత్యక్ష సెన్సార్లు పనిచేస్తున్నాయి"
            "weather_widget_title" -> "ఈరోజు వాతావరణం"
            "live_sensors" -> "ప్రత్యక్ష సెన్సార్లు"
            "soil_moisture" -> "నేల తేమ"
            "water_tank" -> "వాటర్ ట్యాంక్"
            "soil_temp" -> "నేల ఉష్ణోగ్రత"
            "soil_ph" -> "నేల pH స్థాయి"
            "soil_npk" -> "నేల NPK సమతుల్యత"
            "motor_status" -> "మోటార్ పంప్ స్థితి"
            "motor_on" -> "మోటార్ ఆన్"
            "motor_off" -> "మోటార్ ఆఫ్"
            "quick_actions" -> "త్వరిత చర్యలు"
            "latest_scan" -> "ఇటీవలి పంట స్కాన్"
            "expected_yield" -> "అంచనా దిగుబడి"
            "notifications" -> "పొలం నోటిఫికేషన్లు"

            "scan_title" -> "పంట వ్యాధుల గుర్తింపు"
            "upload_image" -> "పంట చిత్రాన్ని అప్‌లోడ్ చేయండి"
            "take_photo" -> "ఫోటో తీయండి"
            "choose_gallery" -> "గ్యాలరీ నుండి ఎంచుకోండి"
            "analyzing" -> "జెమిని AI ద్వారా చిత్రం విశ్లేషించబడుతోంది..."
            "quality_error_title" -> "చిత్ర నాణ్యత తనిఖీ విఫలమైంది"
            "quality_error_msg" -> "దయచేసి ఒకే ప్రభావిత ఆకు లేదా మొక్క యొక్క స్పష్టమైన చిత్రాన్ని అప్‌లోడ్ చేయండి."
            "low_confidence_msg" -> "వ్యాధిని కచ్చితంగా గుర్తించలేకపోయాము. దయచేసి మరింత స్పష్టమైన చిత్రాన్ని అప్‌లోడ్ చేయండి."
            "healthy_plant" -> "ఆరోగ్యకరమైన మొక్క"
            "no_disease" -> "ఏ వ్యాధి గుర్తించబడలేదు. మొక్క పూర్తి ఆరోగ్యంగా ఉంది."
            "report_title" -> "AI వ్యాధి విశ్లేషణ నివేదిక"
            "disease_name" -> "వ్యాధి పేరు"
            "confidence" -> "విశ్వసనీయత స్కోరు"
            "severity" -> "తీవ్రత స్థాయి"
            "affected_part" -> "ప్రభావితమైన భాగం"
            "symptoms" -> "కనిపించే లక్షణాలు"
            "causes" -> "సాధ్యమయ్యే కారణాలు"
            "treatment" -> "సిఫార్సు చేసిన చికిత్స"
            "fungicide" -> "సిఫార్సు చేసిన పురుగుమందు / శిలీంధ్ర నాశిని"
            "organic" -> "సేంద్రీయ నివారణ"
            "prevention" -> "ముందస్తు జాగ్రత్తలు"
            "recovery" -> "కోలుకునే సమయం"
            "farmer_advice" -> "రైతుకు సలహా"
            "crop_rec" -> "పంట వివరాలు"
            "growth_stage" -> "ఎదుగుదల దశ"
            "plant_age" -> "మొక్క వయస్సు"
            "listen_voice" -> "తెలుగులో వినండి"
            "stop_voice" -> "వాయిస్ ఆపండి"

            "irrigation_title" -> "స్మార్ట్ ఆటోమేటిక్ నీటిపారుదల"
            "auto_mode" -> "ఆటోమేటిక్ మోడ్"
            "manual_mode" -> "మాన్యువల్ మోడ్"
            "water_usage" -> "నీటి వినియోగం"
            "last_irrigation" -> "చివరి నీటిపారుదల"
            "next_irrigation" -> "తరువాతి నీటిపారుదల సమయం"
            "liters" -> "లీటర్లు"

            "yield_title" -> "పంట దిగుబడి అంచనా"
            "acres" -> "పొలం విస్తీర్ణం (ఎకరాలు)"
            "seed_variety" -> "విత్తన రకం"
            "expected_harvest" -> "కోత అంచనా తేదీ"
            "market_price" -> "అంచనా మార్కెట్ ధర"
            "est_income" -> "మొత్తం అంచనా ఆదాయం"
            "est_expenses" -> "అంచనా ఖర్చులు"
            "net_profit" -> "నికర లాభం"
            "risk_level" -> "ప్రమాద స్థాయి"
            "yield_suggestions" -> "దిగుబడి పెంచడానికి సూచనలు"

            "weather_title" -> "వాతావరణ సమాచారం"
            "rain_prob" -> "వర్షపాతం సంభావ్యత"
            "wind_speed" -> "గాలి వేగం"
            "uv_index" -> "UV ఇండెక్స్"
            "sunrise" -> "సూర్యోదయం"
            "sunset" -> "సూర్యాస్తమయం"
            "forecast_7day" -> "7 రోజుల వాతావరణ నివేదిక"
            "weather_irrigation_advice" -> "వాతావరణం ఆధారిత నీటిపారుదల సలహా"

            "settings_title" -> "సెట్టింగ్‌లు"
            "theme_mode" -> "యాప్ థీమ్"
            "light_theme" -> "లైట్ థీమ్ (తెలుపు)"
            "dark_theme" -> "డార్క్ థీమ్ (నలుపు)"
            "select_language" -> "భాషను ఎంచుకోండి"
            "farmer_profile" -> "రైతు ప్రొఫైల్"
            "save_profile" -> "ప్రొఫైల్ సేవ్ చేయండి"
            "logout" -> "లాగ్ అవుట్ చేయండి"

            else -> key
        }
    }

    private fun getHindi(key: String): String {
        return when (key) {
            "app_name" -> "क्रॉपकेयर AI"
            "nav_home" -> "डैशबोर्ड"
            "nav_irrigation" -> "स्मार्ट सिंचाई"
            "nav_scan" -> "फ़सल रोग"
            "nav_yield" -> "उपज अनुमान"
            "nav_weather" -> "मौसम"
            "nav_chat" -> "AI सहायक"
            "nav_settings" -> "सेटिंग्स"

            "greeting" -> "नमस्ते"
            "pro_farmer" -> "प्रो किसान"
            "health_score" -> "स्वास्थ्य स्कोर"
            "hero_title" -> "स्मार्ट फ़ार्म नेटवर्क"
            "hero_subtitle" -> "ESP32 लाइव सेंसर सक्रिय"
            "weather_widget_title" -> "आज का मौसम"
            "live_sensors" -> "लाइव सेंसर"
            "soil_moisture" -> "मिट्टी की नमी"
            "water_tank" -> "पानी की टंकी"
            "soil_temp" -> "मिट्टी का तापमान"
            "soil_ph" -> "मिट्टी का pH"
            "soil_npk" -> "मिट्टी NPK संतुलन"
            "motor_status" -> "मोटर पंप की स्थिति"
            "motor_on" -> "मोटर चालू"
            "motor_off" -> "मोटर बंद"
            "quick_actions" -> "त्वरित कार्य"
            "latest_scan" -> "नवीनतम फ़सल स्कैन"
            "expected_yield" -> "अनुमानित उपज"
            "notifications" -> "खेत की सूचनाएं"

            "scan_title" -> "फ़सल रोग पहचान"
            "upload_image" -> "पौधे का चित्र अपलोड करें"
            "take_photo" -> "फोटो लें"
            "choose_gallery" -> "गैलरी से चुनें"
            "analyzing" -> "जेमिनी AI द्वारा चित्र का विश्लेषण हो रहा है..."
            "quality_error_title" -> "चित्र गुणवत्ता जांच विफल"
            "quality_error_msg" -> "कृपया एक ही प्रभावित पत्ती या पौधे की स्पष्ट छवि अपलोड करें।"
            "low_confidence_msg" -> "सटीक रूप से बीमारी की पहचान करने में असमर्थ। कृपया अधिक स्पष्ट छवि अपलोड करें।"
            "healthy_plant" -> "स्वस्थ पौधा"
            "no_disease" -> "कोई बीमारी नहीं पाई गई। पौधा पूरी तरह स्वस्थ है।"
            "report_title" -> "AI रोग विश्लेषण रिपोर्ट"
            "disease_name" -> "रोग का नाम"
            "confidence" -> "सटीकता स्कोर"
            "severity" -> "गंभीरता का स्तर"
            "affected_part" -> "प्रभावित भाग"
            "symptoms" -> "दिखने वाले लक्षण"
            "causes" -> "संभावित कारण"
            "treatment" -> "अनुशंसित उपचार"
            "fungicide" -> "अनुशंसित कीटनाशक / कवकनाशी"
            "organic" -> "जैविक समाधान"
            "prevention" -> "रोकथाम के उपाय"
            "recovery" -> "सुधार का अनुमानित समय"
            "farmer_advice" -> "किसान सलाह"
            "crop_rec" -> "फ़सल का नाम"
            "growth_stage" -> "विकास चरण"
            "plant_age" -> "पौधे की उम्र"
            "listen_voice" -> "हिंदी में सुनें"
            "stop_voice" -> "आवाज रोकें"

            "irrigation_title" -> "स्मार्ट स्वचालित सिंचाई"
            "auto_mode" -> "ऑटो मोड"
            "manual_mode" -> "मैनुअल मोड"
            "water_usage" -> "पानी की खपत"
            "last_irrigation" -> "अंतिम सिंचाई"
            "next_irrigation" -> "अगली अनुशंसित सिंचाई"
            "liters" -> "लीटर"

            "yield_title" -> "फ़सल उपज अनुमान"
            "acres" -> "खेत का आकार (एकड़)"
            "seed_variety" -> "बीज की किस्म"
            "expected_harvest" -> "कटाई की अनुमानित तिथि"
            "market_price" -> "अनुमानित बाज़ार मूल्य"
            "est_income" -> "कुल अनुमानित आय"
            "est_expenses" -> "अनुमानित खर्च"
            "net_profit" -> "शुद्ध लाभ"
            "risk_level" -> "जोखिम का स्तर"
            "yield_suggestions" -> "उपज बढ़ाने के सुझाव"

            "weather_title" -> "मौसम पूर्वानुमान"
            "rain_prob" -> "बारिश की संभावना"
            "wind_speed" -> "हवा की गति"
            "uv_index" -> "UV इंडेक्स"
            "sunrise" -> "सूर्योदय"
            "sunset" -> "सूर्यास्त"
            "forecast_7day" -> "7-दिवसीय मौसम पूर्वानुमान"
            "weather_irrigation_advice" -> "मौसम आधारित सिंचाई सलाह"

            "settings_title" -> "सेटिंग्स"
            "theme_mode" -> "ऐप थीम"
            "light_theme" -> "लाइट थीम (सफेद)"
            "dark_theme" -> "डार्क थीम (काला)"
            "select_language" -> "भाषा चुनें"
            "farmer_profile" -> "किसान प्रोफ़ाइल"
            "save_profile" -> "प्रोफ़ाइल सहेजें"
            "logout" -> "लॉग आउट करें"

            else -> key
        }
    }

    private fun getTamil(key: String): String {
        return when (key) {
            "app_name" -> "கிராப்கேர் AI"
            "nav_home" -> "முகப்பு"
            "nav_irrigation" -> "பாசனம்"
            "nav_scan" -> "பயிர் நோய்"
            "nav_yield" -> "விளைச்சல்"
            "nav_weather" -> "வானிலை"
            "nav_chat" -> "AI உதவியாளர்"
            "nav_settings" -> "அமைப்புகள்"

            "greeting" -> "வணக்கம்"
            "pro_farmer" -> "சிறந்த விவசாயி"
            "health_score" -> "ஆரோக்கிய மதிப்பெண்"
            "hero_title" -> "ஸ்மார்ட் விவசாய நெட்வொர்க்"
            "hero_subtitle" -> "ESP32 சென்சார்கள் இயங்குகின்றன"
            "weather_widget_title" -> "இன்றைய வானிலை"
            "live_sensors" -> "நேரலை சென்சார்கள்"
            "soil_moisture" -> "மண் ஈரம்"
            "water_tank" -> "தண்ணீர் தொட்டி"
            "soil_temp" -> "மண் வெப்பநிலை"
            "soil_ph" -> "மண் pH அளவு"
            "soil_npk" -> "மண் NPK சமநிலை"
            "motor_status" -> "மோட்டார் பம்ப் நிலை"
            "motor_on" -> "மோட்டார் ஆன்"
            "motor_off" -> "மோட்டார் ஆஃப்"
            "quick_actions" -> "விரைவு செயல்பாடுகள்"
            "latest_scan" -> "சமீபத்திய பயிர் ஆய்வு"
            "expected_yield" -> "எதிர்பார்க்கப்படும் விளைச்சல்"
            "notifications" -> "பண்ணை அறிவிப்புகள்"

            "scan_title" -> "பயிர் நோய் கண்டறிதல்"
            "upload_image" -> "பயிர் படத்தை பதிவேற்றவும்"
            "take_photo" -> "படம் எடுக்கவும்"
            "choose_gallery" -> "கேலரியில் தேர்ந்தெடுக்கவும்"
            "analyzing" -> "ஜெமினி AI மூலம் ஆய்வு செய்யப்படுகிறது..."
            "quality_error_title" -> "படத்தின் தரம் போதாது"
            "quality_error_msg" -> "தயவுசெய்து பாதிக்கப்பட்ட ஒற்றை இலையின் தெளிவான படத்தை பதிவேற்றவும்."
            "low_confidence_msg" -> "நோயை துல்லியமாக கண்டறிய முடியவில்லை. தெளிவான படத்தை பதிவேற்றவும்."
            "healthy_plant" -> "ஆரோக்கியமான பயிர்"
            "no_disease" -> "எந்த நோயும் கண்டறியப்படவில்லை. பயிர் ஆரோக்கியமாக உள்ளது."
            "report_title" -> "AI நோய் ஆய்வு அறிக்கை"
            "disease_name" -> "நோயின் பெயர்"
            "confidence" -> "துல்லியம்"
            "severity" -> "பாதிப்பு நிலை"
            "affected_part" -> "பாதிக்கப்பட்ட பகுதி"
            "symptoms" -> "அறிகுறிகள்"
            "causes" -> "காரணங்கள்"
            "treatment" -> "பரிந்துரைக்கப்பட்ட சிகிச்சை"
            "fungicide" -> "பூச்சிக்கொல்லி / பூஞ்சான்கொல்லி"
            "organic" -> "இயற்கை தீர்வு"
            "prevention" -> "முன்னெச்சரிக்கை நடவடிக்கைகள்"
            "recovery" -> "குணமடையும் காலம்"
            "farmer_advice" -> "விவசாயி ஆலோசனை"
            "crop_rec" -> "பயிர் விவரம்"
            "growth_stage" -> "வளர்ச்சி நிலை"
            "plant_age" -> "பயிரின் வயது"
            "listen_voice" -> "தமிழில் கேட்கவும்"
            "stop_voice" -> "நிறுத்தவும்"

            "irrigation_title" -> "தானியங்கி நீர்ப்பாசனம்"
            "auto_mode" -> "தானியங்கி முறை"
            "manual_mode" -> "கைமுறை"
            "water_usage" -> "தண்ணீர் பயன்பாடு"
            "last_irrigation" -> "கடைசி பாசனம்"
            "next_irrigation" -> "அடுத்த பாசன நேரம்"
            "liters" -> "லிட்டர்கள்"

            "yield_title" -> "விளைச்சல் கணிப்பு"
            "acres" -> "பண்ணை அளவு (ஏக்கர்)"
            "seed_variety" -> "விதை ரகம்"
            "expected_harvest" -> "அறுவடை தேதி"
            "market_price" -> "சந்தை விலை"
            "est_income" -> "வருமானம்"
            "est_expenses" -> "செலவு"
            "net_profit" -> "நிகர லாபம்"
            "risk_level" -> "ஆபத்து நிலை"
            "yield_suggestions" -> "விளைச்சலை உயர்த்த ஆலோசனைகள்"

            "weather_title" -> "வானிலை தகவல்"
            "rain_prob" -> "மழை வாய்ப்பு"
            "wind_speed" -> "காற்றின் வேகம்"
            "uv_index" -> "UV குறியீடு"
            "sunrise" -> "சூரியோதயம்"
            "sunset" -> "சூரிய அஸ்தமனம்"
            "forecast_7day" -> "7 நாள் வானிலை அறிக்கை"
            "weather_irrigation_advice" -> "வானிலை பாசன ஆலோசனை"

            "settings_title" -> "அமைப்புகள்"
            "theme_mode" -> "தீம்"
            "light_theme" -> "லைட் தீம் (வெள்ளை)"
            "dark_theme" -> "டார்க் தீம் (கருப்பு)"
            "select_language" -> "மொழியை தேர்ந்தெடுக்கவும்"
            "farmer_profile" -> "விவசாயி சுயவிவரம்"
            "save_profile" -> "சேமிக்கவும்"
            "logout" -> "வெளியேறு"

            else -> key
        }
    }

    private fun getKannada(key: String): String {
        return when (key) {
            "app_name" -> "ಕ್ರಾಪ್‌ಕೇರ್ AI"
            "nav_home" -> "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್"
            "nav_irrigation" -> "ನೀರಾವರಿ"
            "nav_scan" -> "ಬೆಳೆ ರೋಗ"
            "nav_yield" -> "ಇಳುವರಿ"
            "nav_weather" -> "ಹವಾಮಾನ"
            "nav_chat" -> "AI ಸಹಾಯಕ"
            "nav_settings" -> "ಸಜ್ಜಿಕೆಗಳು"

            "greeting" -> "ನಮಸ್ಕಾರ"
            "pro_farmer" -> "ಪ್ರೋ ರೈತ"
            "health_score" -> "ಆರೋಗ್ಯ ಸ್ಕೋರ್"
            "hero_title" -> "ಸ್ಮಾರ್ಟ್ ಫಾರ್ಮ್ ನೆಟ್‌ವರ್ಕ್"
            "hero_subtitle" -> "ESP32 ಸೆನ್ಸಾರ್‌ಗಳು ಸಕ್ರಿಯವಾಗಿವೆ"
            "weather_widget_title" -> "ಇಂದಿನ ಹವಾಮಾನ"
            "live_sensors" -> "ಲೈವ್ ಸೆನ್ಸಾರ್‌ಗಳು"
            "soil_moisture" -> "ಮಣ್ಣಿನ ತೇವಾಂಶ"
            "water_tank" -> "ನೀರಿನ ಟ್ಯಾಂಕ್"
            "soil_temp" -> "ಮಣ್ಣಿನ ತಾಪಮಾನ"
            "soil_ph" -> "ಮಣ್ಣಿನ pH ಮಟ್ಟ"
            "soil_npk" -> "ಮಣ್ಣಿನ NPK ಸಮತೋಲನ"
            "motor_status" -> "ಮೋಟಾರ್ ಪಂಪ್ ಸ್ಥಿತಿ"
            "motor_on" -> "ಮೋಟಾರ್ ಆನ್"
            "motor_off" -> "ಮೋಟಾರ್ ಆಫ್"
            "quick_actions" -> "ತ್ವರಿತ ಕಾರ್ಯಗಳು"
            "latest_scan" -> "ಇತ್ತೀಚಿನ ಬೆಳೆ ಸ್ಕ್ಯಾನ್"
            "expected_yield" -> "ನಿರೀಕ್ಷಿತ ಇಳುವರಿ"
            "notifications" -> "ಜಮೀನಿನ ಸೂಚನೆಗಳು"

            "scan_title" -> "ಬೆಳೆ ರೋಗ ಪತ್ತೆ"
            "upload_image" -> "ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ"
            "take_photo" -> "ಫೋಟೋ ತೆಗೆಯಿರಿ"
            "choose_gallery" -> "ಗ್ಯಾಲರಿಯಿಂದ ಆಯ್ಕೆಮಾಡಿ"
            "analyzing" -> "ಜೆಮಿನಿ AI ವಿಶ್ಲೇಷಿಸುತ್ತಿದೆ..."
            "quality_error_title" -> "ಚಿತ್ರದ ಗುಣಮಟ್ಟ ಸಾಲದು"
            "quality_error_msg" -> "ದಯವಿಟ್ಟು ಬಾಧಿತ ಎಲೆಯ ಸ್ಪಷ್ಟ ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ."
            "low_confidence_msg" -> "ರೋಗವನ್ನು ನಿಖರವಾಗಿ ಪತ್ತೆಹಚ್ಚಲು ಸಾಧ್ಯವಾಗುತ್ತಿಲ್ಲ. ಸ್ಪಷ್ಟ ಫೋಟೋ ಹಾಕಿ."
            "healthy_plant" -> "ಆರೋಗ್ಯಕರ ಸಸ್ಯ"
            "no_disease" -> "ಯಾವುದೇ ರೋಗ ಕಂಡುಬಂದಿಲ್ಲ. ಸಸ್ಯವು ಆರೋಗ್ಯಕರವಾಗಿದೆ."
            "report_title" -> "AI ರೋಗ ವಿಶ್ಲೇಷಣೆ ವರದಿ"
            "disease_name" -> "ರೋಗದ ಹೆಸರು"
            "confidence" -> "ನಿಖರತೆ"
            "severity" -> "ತೀವ್ರತೆಯ ಮಟ್ಟ"
            "affected_part" -> "ಬಾಧಿತ ಭಾಗ"
            "symptoms" -> "ಲಕ್ಷಣಗಳು"
            "causes" -> "ಸಾಧ್ಯವಾದ ಕಾರಣಗಳು"
            "treatment" -> "ಶಿಫಾರಸು ಮಾಡಿದ ಚಿಕಿತ್ಸೆ"
            "fungicide" -> "ಔಷಧಿ / ಕೀಟನಾಶಕ"
            "organic" -> "ಸಾವಯವ ಪರಿಹಾರ"
            "prevention" -> "ಮುನ್ನೆಚ್ಚರಿಕೆ ಕ್ರಮಗಳು"
            "recovery" -> "ಚೇತರಿಕೆಯ ಸಮಯ"
            "farmer_advice" -> "ರೈತರಿಗೆ ಸಲಹೆ"
            "crop_rec" -> "ಬೆಳೆ ವಿವರ"
            "growth_stage" -> "ಬೆಳವಣಿಗೆಯ ಹಂತ"
            "plant_age" -> "ಸಸ್ಯದ ವಯಸ್ಸು"
            "listen_voice" -> "ಕನ್ನಡದಲ್ಲಿ ಕೇಳಿ"
            "stop_voice" -> "ನಿಲ್ಲಿಸಿ"

            "irrigation_title" -> "ಸ್ವಯಂಚಾಲಿತ ನೀರಾವರಿ"
            "auto_mode" -> "ಆಟೋ ಮೋಡ್"
            "manual_mode" -> "ಮ್ಯಾನುಯಲ್"
            "water_usage" -> "ನೀರಿನ ಬಳಕೆ"
            "last_irrigation" -> "ಕೊನೆಯ ನೀರಾವರಿ"
            "next_irrigation" -> "ಮುಂದಿನ ನೀರಾವರಿ ಸಮಯ"
            "liters" -> "ಲೀಟರ್‌ಗಳು"

            "yield_title" -> "ಇಳುವರಿ ಅಂದಾಜು"
            "acres" -> "ಜಮೀನಿನ ಗಾತ್ರ (ಎಕರೆ)"
            "seed_variety" -> "ಬೀಜದ ತಳಿ"
            "expected_harvest" -> "ಕೊಯ್ಲಿನ ದಿನಾಂಕ"
            "market_price" -> "ಮಾರುಕಟ್ಟೆ ಬೆಲೆ"
            "est_income" -> "ಆದಾಯ"
            "est_expenses" -> "ಖರ್ಚು"
            "net_profit" -> "ನಿವ್ವಳ ಲಾಭ"
            "risk_level" -> "ಅಪಾಯದ ಮಟ್ಟ"
            "yield_suggestions" -> "ಇಳುವರಿ ಹೆಚ್ಚಿಸಲು ಸಲಹೆಗಳು"

            "weather_title" -> "ಹವಾಮಾನ ಮಾಹಿತಿ"
            "rain_prob" -> "ಮಳೆಯ ಮುನ್ಸೂಚನೆ"
            "wind_speed" -> "ಗಾಳಿಯ ವೇಗ"
            "uv_index" -> "UV ಸೂಚ್ಯಂಕ"
            "sunrise" -> "ಸೂರ್ಯೋದಯ"
            "sunset" -> "ಸೂರ್ಯಾಸ್ತ"
            "forecast_7day" -> "7 ದಿನಗಳ ಹವಾಮಾನ ವರದಿ"
            "weather_irrigation_advice" -> "ಹವಾಮಾನ ಆಧಾರಿತ ನೀರಾವರಿ ಸಲಹೆ"

            "settings_title" -> "ಸಜ್ಜಿಕೆಗಳು"
            "theme_mode" -> "ಥೀಮ್"
            "light_theme" -> "ಲೈಟ್ ಥೀಮ್ (ಬಿಳಿ)"
            "dark_theme" -> "ಡಾರ್ಕ್ ಥೀಮ್ (ಕಪ್ಪು)"
            "select_language" -> "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ"
            "farmer_profile" -> "ರೈತರ ಪ್ರೊಫೈಲ್"
            "save_profile" -> "ಸೇವ್ ಮಾಡಿ"
            "logout" -> "ಲಾಗ್ ಔಟ್"

            else -> key
        }
    }

    private fun getMalayalam(key: String): String {
        return when (key) {
            "app_name" -> "ക്രോപ്പ്കെയർ AI"
            "nav_home" -> "ഡാഷ്‌ബോർഡ്"
            "nav_irrigation" -> "നനയ്ക്കൽ"
            "nav_scan" -> "വിള രോഗങ്ങൾ"
            "nav_yield" -> "വിളവ് പ്രവചനം"
            "nav_weather" -> "കാലാവസ്ഥ"
            "nav_chat" -> "AI സഹായി"
            "nav_settings" -> "ക്രമീകരണങ്ങൾ"

            "greeting" -> "നമസ്കാരം"
            "pro_farmer" -> "പ്രോ കർഷകൻ"
            "health_score" -> "ആരോഗ്യ സ്കോർ"
            "hero_title" -> "സ്മാർട്ട് ഫാം നെറ്റ്‌വർക്ക്"
            "hero_subtitle" -> "ESP32 സെൻസറുകൾ പ്രവർത്തിക്കുന്നു"
            "weather_widget_title" -> "ഇന്നത്തെ കാലാവസ്ഥ"
            "live_sensors" -> "ലൈവ് സെൻസറുകൾ"
            "soil_moisture" -> "മണ്ണിലെ ഈർപ്പം"
            "water_tank" -> "വാട്ടർ ടാങ്ക്"
            "soil_temp" -> "മണ്ണിന്റെ താപനില"
            "soil_ph" -> "മണ്ണിന്റെ pH ലെവൽ"
            "soil_npk" -> "മണ്ണിലെ NPK തോത്"
            "motor_status" -> "മോട്ടോർ പമ്പ് അവസ്ഥ"
            "motor_on" -> "മോട്ടോർ ഓൺ"
            "motor_off" -> "മോട്ടോർ ഓഫ്"
            "quick_actions" -> "വേഗത്തിലുള്ള നടപടികൾ"
            "latest_scan" -> "ഏറ്റവും പുതിയ വിള സ്കാൻ"
            "expected_yield" -> "പ്രതീക്ഷിക്കുന്ന വിളവ്"
            "notifications" -> "ഫാം അറിയിപ്പുകൾ"

            "scan_title" -> "വിള രോഗനിർണ്ണയം"
            "upload_image" -> "ചിത്രം അപ്‌ലോഡ് ചെയ്യുക"
            "take_photo" -> "ഫോട്ടോ എടുക്കുക"
            "choose_gallery" -> "ഗാലറിയിൽ നിന്ന് തിരഞ്ഞെടുക്കുക"
            "analyzing" -> "ജെമിനി AI വഴി പരിശോധിക്കുന്നു..."
            "quality_error_title" -> "ചിത്രത്തിന്റെ ഗുണനിലവാരം കുറവാണ്"
            "quality_error_msg" -> "ബാധിക്കപ്പെട്ട ഇലയുടെ വ്യക്തമായ ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക."
            "low_confidence_msg" -> "രോഗം കൃത്യമായി കണ്ടെത്താനായില്ല. വ്യക്തമായ ഫോട്ടോ ഇടുക."
            "healthy_plant" -> "ആരോഗ്യമുള്ള ചെടി"
            "no_disease" -> "രോഗങ്ങളൊന്നും കണ്ടെത്തിയില്ല. ചെടി പൂർണ്ണ ആരോഗ്യത്തിലാണ്."
            "report_title" -> "AI രോഗ വിശകലന റിപ്പോർട്ട്"
            "disease_name" -> "രോഗത്തിന്റെ പേര്"
            "confidence" -> "കൃത്യത"
            "severity" -> "തീവ്രത"
            "affected_part" -> "ബാധിച്ച ഭാഗം"
            "symptoms" -> "ലക്ഷണങ്ങൾ"
            "causes" -> "കാരണങ്ങൾ"
            "treatment" -> "ശിപാർശ ചെയ്ത ചികിത്സ"
            "fungicide" -> "കീടനാശിനി / മരുന്ന്"
            "organic" -> "ജൈവ രീതി"
            "prevention" -> "മുൻകരുതലുകൾ"
            "recovery" -> "രോഗശാന്തി സമയം"
            "farmer_advice" -> "കർഷകന് ഉപദേശം"
            "crop_rec" -> "വിള വിവരങ്ങൾ"
            "growth_stage" -> "വളർച്ചാ ഘട്ടം"
            "plant_age" -> "ചെടിയുടെ പ്രായം"
            "listen_voice" -> "മലയാളത്തിൽ കേൾക്കുക"
            "stop_voice" -> "നിർത്തുക"

            "irrigation_title" -> "ഓട്ടോമാറ്റിക് നനയ്ക്കൽ"
            "auto_mode" -> "ഓട്ടോ മോഡ്"
            "manual_mode" -> "മാനുവൽ മോഡ്"
            "water_usage" -> "വെള്ളത്തിന്റെ ഉപയോഗം"
            "last_irrigation" -> "അവസാന നനയ്ക്കൽ"
            "next_irrigation" -> "അടുത്ത നനയ്ക്കൽ സമയം"
            "liters" -> "ലിറ്ററുകൾ"

            "yield_title" -> "വിളവ് പ്രവചനം"
            "acres" -> "സ്ഥലത്തിന്റെ അളവ് (ഏക്കർ)"
            "seed_variety" -> "വിത്തിന്റെ ഇനം"
            "expected_harvest" -> "വിളവെടുപ്പ് തീയതി"
            "market_price" -> "വിപണി വില"
            "est_income" -> "വരുമാനം"
            "est_expenses" -> "ചെലവ്"
            "net_profit" -> "അറ്റാദായം"
            "risk_level" -> "സാധ്യത ലെവൽ"
            "yield_suggestions" -> "വിളവ് കൂട്ടാൻ നിർദ്ദേശങ്ങൾ"

            "weather_title" -> "കാലാവസ്ഥ വിവരങ്ങൾ"
            "rain_prob" -> "മഴയ്ക്കുള്ള സാധ്യത"
            "wind_speed" -> "കാറ്റിന്റെ വേഗത"
            "uv_index" -> "UV സൂചിക"
            "sunrise" -> "സൂര്യോദയം"
            "sunset" -> "സൂര്യാസ്തമയം"
            "forecast_7day" -> "7 ദിവസത്തെ കാലാവസ്ഥ പ്രവചനം"
            "weather_irrigation_advice" -> "കാലാവസ്ഥാധിഷ്ഠിത നനയ്ക്കൽ ഉപദേശം"

            "settings_title" -> "ക്രമീകരണങ്ങൾ"
            "theme_mode" -> "തീം"
            "light_theme" -> "ലൈറ്റ് തീം (വെളുപ്പ്)"
            "dark_theme" -> "ഡാർക്ക് തീം (കറുപ്പ്)"
            "select_language" -> "ഭാഷ തിരഞ്ഞെടുക്കുക"
            "farmer_profile" -> "കർഷക പ്രൊഫൈൽ"
            "save_profile" -> "സേവ് ചെയ്യുക"
            "logout" -> "ലോഗ് ഔട്ട്"

            else -> key
        }
    }
}
